version: '3'
services:
  db:
    image: mongo
    # volumes: 
    # environment/db/mongod.conf:/etc/mongod.conf
    # ./db:/var/lib/mongodb
    restart: always
    ports: [27017:27017]

  web:
    # Build the dockerfile in the app
    build: ./app
    restart: always
    ports: [3000:3000]
    environment:
      - DB_HOST=mongodb://db:27017/posts
    depends_on:
      - db



